#ifndef COLORS_H
#define COLORS_H

typedef enum {
    COLOR_PAIR_RED = 1, 
    COLOR_PAIR_GREEN, 
    COLOR_PAIR_BLUE, 
    COLOR_PAIR_YELLOW,

    COLOR_PAIR_NONE,
    COLOR_PAIR_GRASS,
    COLOR_PAIR_WHEAT,
    COLOR_PAIR_WATER,
    COLOR_PAIR_STONE,
    COLOR_PAIR_TREE,

    COLOR_PAIR_TEXT_BW,
} Color_Pair;

#endif